### ISSUE TITLE
Homekit Configuration Code not accepted

### ISSUE THREAD

**Issue by gerardwr** [AchimPieters/ESP8266-HomeKit-Motion-Sensor#1]
Hi,

I have been trying some of your Homekit projects on an ESP8266.

For instance, the ESP8266-Homekit_Switch works nicely. The documentation is excellent, and downloading the firmware and adding the device in the Home App using the QRCODE works fine.

But the ESP8266-Homekit-Motion-Sensor binary fails in the IOS Home App:
- The device is recognised as Motion Sensor-9F812A-DEE7
- but when I enter the Homekit Configuration Code (558-98-144 as found in main.c) the Home App reports "Motion Sensor ....... toevoegen mislukt. De configuratiecode is onjuist". See screendump of final output in Arduino Serial Monitor

Would appreciate if you can help me solve this issue.

Kind regards,
Gerard.

<img width="1188" alt="Schermafbeelding 2019-09-28 om 18 36 13" src="https://user-images.githubusercontent.com/10114857/65819794-30152100-e221-11e9-9681-c1ec19b7b2a3.png">

**Comment by AchimPieters** [comment]
@gerardwr I just made a quick setup and tested it once again, but it works fine. You probably didn't scan the QR Code, it's in the folder images. Here is the direct link.

https://raw.githubusercontent.com/AchimPieters/ESP8266-HomeKit-Motion-Sensor/master/images/qrcode.png

The blog on https://studiopieters isn't posted yet.

**Comment by gerardwr** [comment]
Hello Achim,

Thanks for your help.

You're right, I thought the QR code was missing so I thought I could use the password code 558-98-144 from main.c.

With the QR code from the images folder, adding the Motion Sensor to the Home App works without problems.

Output from the Arduino Serial Monitor below shows that the Motion Sensor on GPIO12 is working.

Appreciate your help, thanks for sharing your work and knowledge.

````
13:59:35.563 -> mDNS announcement: Name=Motion Sensor-9F812A-D509 md=Motion Sensorpv=1.0id=D5:09:7A:1C:91:70c#=1s#=1ff=0sf=0ci=10sh=j8gDnQ== Port=5556 TTL=4500
13:59:35.992 -> >>> HomeKit: Got new client connection: 4
13:59:35.992 -> >>> HomeKit: [Client 4] Pair Verify Step 1/2
13:59:36.438 -> >>> HomeKit: [Client 4] Pair Verify Step 2/2
13:59:36.438 -> >>> HomeKit: [Client 4] Found pairing with 79D9ADAF-20C1-461B-9A5F-3C6E47592998
13:59:36.583 -> >>> HomeKit: [Client 4] Verification successful, secure session established
13:59:36.618 -> >>> HomeKit: [Client 4] Get Accessories
13:59:36.909 -> >>> HomeKit: [Client 4] Update Characteristics
13:59:36.909 -> >>> HomeKit: [Client 4] Update Characteristics
13:59:36.944 -> >>> HomeKit: [Client 4] Get Characteristics
14:00:07.120 -> Motion Detected on 12
14:00:07.120 -> Motion Stopped on 12
14:00:07.158 -> Motion Stopped on 12
14:00:07.158 -> Motion Detected on 12

**Comment by gerardwr** [comment]
For any other readers : I just learned that the QR code must be generated with a special tool using the password and setUpId information in the main.c code.

Details here :https://github.com/maximkulkin/esp-homekit/tree/master#qr-code-pairing

**Comment by AchimPieters** [comment]
@gerardwr I already described that part here: https://www.studiopieters.nl/esp-homekit-sdk-qr-code
