### ISSUE TITLE
Wemos D1 mini with Motion Sensor

### ISSUE THREAD

**Issue by KitesAir** [AchimPieters/ESP8266-HomeKit-Motion-Sensor#4]
Hi Achim Pieters,

Thank you a lot for your guide to implement HomeKit on ESP8266. I have tried to deploy on Wemos D1 mini. I successfully added the sensor to Home but it can't trigger. Here is my setup. Could you please help me out?

![IMG_5815](https://user-images.githubusercontent.com/66745754/99143209-31581600-268e-11eb-9344-2ba4a1017310.jpg)

ESP8266 <-> SENSOR
G <-> G
D7 <-> OUT
VCC <-> 3V3

On my iPhone. The motion Detected is always NO
![IMG_5816](https://user-images.githubusercontent.com/66745754/99143248-957ada00-268e-11eb-884f-72967c2848be.PNG)

**Comment by AchimPieters** [comment]
@KitesAir More information about the setup you can find here: https://www.studiopieters.nl/esp8266-homekit-motion-sensor
But the problem I think lies with the sensor, you need to adjust it to sense something this information can be found here: https://www.studiopieters.nl/hc-sr501-motion-sensor/

**Comment by KitesAir** [comment]
@AchimPieters Thank you very much. I adjusted the delay and REPEATED mode so it's working.
